read_verilog -sv ../design/swerv_wrapper.sv
read_verilog -sv ../design/mem.sv
read_verilog -sv ../design/pic_ctrl.sv
read_verilog -sv ../design/swerv.sv
read_verilog -sv ../design/dma_ctrl.sv
read_verilog -sv ../design/ifu/ifu_aln_ctl.sv
read_verilog -sv ../design/ifu/ifu_compress_ctl.sv
read_verilog -sv ../design/ifu/ifu_ifc_ctl.sv
read_verilog -sv ../design/ifu/ifu_bp_ctl.sv
read_verilog -sv ../design/ifu/ifu_ic_mem.sv
read_verilog -sv ../design/ifu/ifu_mem_ctl.sv
read_verilog -sv ../design/ifu/ifu_iccm_mem.sv
read_verilog -sv ../design/ifu/ifu.sv
read_verilog -sv ../design/dec/dec_decode_ctl.sv
read_verilog -sv ../design/dec/dec_gpr_ctl.sv
read_verilog -sv ../design/dec/dec_ib_ctl.sv
read_verilog -sv ../design/dec/dec_tlu_ctl.sv
read_verilog -sv ../design/dec/dec_trigger.sv
read_verilog -sv ../design/dec/dec.sv
read_verilog -sv ../design/exu/exu_alu_ctl.sv
read_verilog -sv ../design/exu/exu_mul_ctl.sv
read_verilog -sv ../design/exu/exu_div_ctl.sv
read_verilog -sv ../design/exu/exu.sv
read_verilog -sv ../design/lsu/lsu.sv
read_verilog -sv ../design/lsu/lsu_clkdomain.sv
read_verilog -sv ../design/lsu/lsu_addrcheck.sv
read_verilog -sv ../design/lsu/lsu_lsc_ctl.sv
read_verilog -sv ../design/lsu/lsu_stbuf.sv
read_verilog -sv ../design/lsu/lsu_bus_read_buffer.sv
read_verilog -sv ../design/lsu/lsu_bus_write_buffer.sv
read_verilog -sv ../design/lsu/lsu_bus_intf.sv
read_verilog -sv ../design/lsu/lsu_ecc.sv
read_verilog -sv ../design/lsu/lsu_dccm_mem.sv
read_verilog -sv ../design/lsu/lsu_dccm_ctl.sv
read_verilog -sv ../design/lsu/lsu_trigger.sv
read_verilog -sv ../design/dbg/dbg.sv
read_verilog -sv ../design/dmi/dmi_wrapper.v
read_verilog -sv ../design/dmi/dmi_jtag_to_core_sync.v
read_verilog -sv ../design/dmi/rvjtag_tap.v
read_verilog -sv ../design/dmi/double_flop_sync.v
read_verilog -sv ../design/dmi/toggle_sync.v
read_verilog -sv ../design/lib/beh_lib.sv
read_verilog -sv ../design/lib/mem_lib.sv
read_verilog -sv ../design/lib/ahb_to_axi4.sv
read_verilog -sv ../design/lib/axi4_to_ahb.sv
